### ISSUE TITLE
Additional information field for data model?

### ISSUE THREAD

**Issue by robcast** [dh-tech/undate-python#25]
Should we add a string notes field for additional information to the data model?

This field would be separate from the `label` field, which is just a printable representation of the date (I assume). The additional information field could contain information from the original source that is not represented in the date object, like "On a Sunday morning". 

One could argue that this field does not have to be in the date data model but it should be in the data model of the application that uses the date.

Our ISMI data (see #17)  currently has such a field and we need to keep the information in the migration.

**Comment by rlskoeser** [comment]
From the discussion at our kickoff meeting, I was thinking that the label field would be optional additional information or a name for the date or time period (e.g., something like "The Renaissance" or maybe "Easter 1919") — so maybe the text you have could fit there?

**Comment by rlskoeser** [comment]
I'm going to close this issue because our existing label field is meant for exactly this purpose - it's an optional field for additional information or description of the date. We can think more about what we want to do with this field; it should probably be integrated into some of the string methods, but I'm not sure how we'd decide when/if you want the label and when you don'.
